font_family JetBrainsMono Nerd Font Mono
font_size 13
font_features JetBrainsMonoNFM-Regular +calt +liga +ss01

background_opacity 0.90
background_blur 20

cursor_shape block
cursor_blink_interval 0

shell_integration no-cursor

hide_window_decorations yes
tab_bar_style hidden
macos_option_as_alt both

include themes/kanso_ink.conf
cursor none
