# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'nordtheme/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

#---------------------------------------------------------------

set-option -sa terminal-overrides ",xterm*:Tc"

set -g status-right-length 52
set -g status-style bg=default
set -g window-status-style bg=default
set -g window-status-current-style bg=default

set -g prefix C-t
unbind C-b
bind-key C-t send-prefix

setw -g mouse on

bind-key v split-window -h -c "#{pane_current_path}"
bind-key s split-window -v -c "#{pane_current_path}"
bind-key H select-pane -L
bind-key J select-pane -D
bind-key K select-pane -U
bind-key L select-pane -R
bind-key -r -T prefix       Up              resize-pane -U 5
bind-key -r -T prefix       Down            resize-pane -D 5
bind-key -r -T prefix       Left            resize-pane -L 5
bind-key -r -T prefix       Right           resize-pane -R 5

bind-key ! break-pane -d -n _hidden_pane
bind-key @ join-pane -s 1 

bind-key R source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

bind-key C-o rotate-window

set-option -g default-command "/bin/bash -c 'which reattach-to-user-namespace >/dev/null && exec reattach-to-user-namespace $SHELL -l || exec $SHELL -l'"
set-option -g renumber-windows on

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
