# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

#---------------------------------------------------------------

set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",xterm*:Tc"
set-option -ga terminal-overrides ",tmux-256color:Tc"

# Kanagawa Dragon colors
set -g status-style "bg=#181616 fg=#c5c9c5"
set -g status-left-style "bg=#181616 fg=#87a987 bold"
set -g status-right ""
set -g status-right-length 0
set -g window-status-style "bg=#181616 fg=#a8a8a8"
set -g window-status-current-style "bg=#181616 fg=#C4746E bold"
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
set -g pane-border-style "fg=#282727"
set -g pane-active-border-style "fg=#C4746E"
set -g message-style "bg=#181616 fg=#c5c9c5"

set -g prefix C-t
unbind C-b
bind-key C-t send-prefix

setw -g mouse on

bind-key v split-window -h -c "#{pane_current_path}"
bind-key s split-window -v -c "#{pane_current_path}"
unbind l
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key -r -T prefix       Up              resize-pane -U 5
bind-key -r -T prefix       Down            resize-pane -D 5
bind-key -r -T prefix       Left            resize-pane -L 5
bind-key -r -T prefix       Right           resize-pane -R 5

bind-key ! break-pane -d -n _hidden_pane
bind-key @ join-pane -s 1 

bind-key R source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

bind-key C-o rotate-window

set-option -g default-command "/bin/bash -c 'which reattach-to-user-namespace >/dev/null && exec reattach-to-user-namespace $SHELL -l || exec $SHELL -l'"
set-option -g renumber-windows on

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
